name: CI

on:
  # Post-submit.
  push:
    branches: [main]

  # Pre-submit.
  pull_request:
    branches: [main]

  # Cron job: Every 12 hours.
  schedule:
    - cron: "0 */12 * *"

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v3.6
      - run: flutter doctor
      - name: Run Tests
        uses: futureware-tech/simulator-action@v3
      - run: flutter drive --driver=test/xcrun_simctl_screenshot_test.dart
