name: flutter_ios_screenshot
description: "An iOS app, with Flutter, that takes a screenshot."

environment:
  sdk: ^3.6.0-175.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  matcher: ^0.12.16+1
  test: ^1.25.8
  path: ^1.9.0

flutter:
  uses-material-design: true
